clean up code
m1stadev/PyIMG4 pull request #2
Opened 2022-04-09 17:00 UTC by justtryingthingsout

2022-04-10 07:44 UTC, nyuszika7h requested changes

2022-04-10 07:44 UTC, nyuszika7h commented on pyimg4/parser.py
> +        return f"Keybag(iv={format(self.iv, 'x')}, key={format(self.key, 'x')}, type={self.type.name})"
```suggestion
        return f"Keybag(iv={self.iv:x}, key={self.key:x}, type={self.type.name})"
```

2022-04-12 01:48 UTC, m1stadev requested changes

2022-04-12 01:48 UTC, m1stadev commented on pyimg4/parser.py
> +        return f"Keybag(iv={format(self.iv, 'x')}, key={format(self.key, 'x')}, type={self.type.name})"
`format()` doesn't look like its available for `bytes` objects.

2022-04-12 02:18 UTC, m1stadev requested changes

2022-04-12 02:18 UTC, m1stadev commented on pyimg4/parser.py
> +        elif self.decoder.peek().nr != asn1.Numbers.Set:
I'd rather this stay as an `if` statement, just to make it a bit more readable.

2022-04-12 02:31 UTC, merged