Add verify-shsh
m1stadev/PyIMG4 pull request #24
Opened 2023-02-04 01:22 UTC by Karma2424

2023-02-04 17:04 UTC, m1stadev requested changes
What does this fix?

2023-02-04 21:22 UTC, Karma2424 commented
> What does adding the 0 to the board id in im4m_verify fix?

if you hex `26` it turns to `0x1a` which in `a` is not capital so does not match `identity['ApBoardID']` as it is `0x1A` as you can see it is a problem and also there is other problem as some devices `ApBoardID` is only one hex character long eg hex `12` turns into `0xc` which does not match the `0x0C` in `identity['ApBoardID']` check this for all `ApBoardID` apple uses [https://www.theiphonewiki.com/wiki/BORD](url)

> referring to your last commit message, using PyIMG4's CLI vs this example script still requires PyIMG4 to be installed, which will require compilation. 

when I say it will not require compilation on windows I was referring tihmstar's img4tool as it not available on windows precompiled

2023-02-06 06:31 UTC, m1stadev requested changes

2023-02-06 06:31 UTC, m1stadev commented on pyimg4/__main__.py
> +        if identity['ApBoardID'] != board_id and identity['ApChipID'] != hex(im4m.chip_id):
It would be much more efficient to convert `identity['ApBoardID']` and `identity['ApChipID']` to integers, since they're just hexadecimal numbers stored as strings:
```suggestion
    for identity in manifest['BuildIdentities']:
        if not (
            int(identity['ApBoardID'], 16) == im4m.board_id
            and int(identity['ApChipID'], 16) == im4m.chip_id
        ):
```

2023-02-06 06:31 UTC, m1stadev commented on examples/verify-shsh.py
> +    main(build_manifest_path=args.build_manifest, shsh_path=args.shsh, verbose=args.verbose)
I don't really see a huge need to add an example script for this, as PyIMG4's CLI can already verify Image4 manifests with a provided build manifest. The only difference between the CLI's implementation and this is that this uses an SHSH blob instead of an Image4 manifest directly, but it's already trivial to extract an Image4 manifest from an SHSH blob :/

2023-02-06 23:37 UTC, liveroverflow commented on pyimg4/__main__.py
> +        if identity['ApBoardID'] != board_id and identity['ApChipID'] != hex(im4m.chip_id):
yep this is indeed more pleasant than the dirty fix I presented

2023-02-07 00:42 UTC, liveroverflow commented on examples/verify-shsh.py
> +    main(build_manifest_path=args.build_manifest, shsh_path=args.shsh, verbose=args.verbose)
Yeah as I said before there really is not a easy way to check SHSH blob validity on windows and adding this script would end that but Ideally you would want a way to check SHSH validity directly integrated into PyIMG4's CLI until then this should suffice.

2023-02-07 01:14 UTC, Karma2424 commented on pyimg4/__main__.py
> +        if identity['ApBoardID'] != board_id and identity['ApChipID'] != hex(im4m.chip_id):
yep this is indeed more pleasant than the dirty fix I presented

2023-02-07 01:14 UTC, Karma2424 commented on examples/verify-shsh.py
> +    main(build_manifest_path=args.build_manifest, shsh_path=args.shsh, verbose=args.verbose)
Yeah as I said before there really is not a easy way to check SHSH blob validity on windows and adding this script would end that but Ideally you would want a way to check SHSH validity directly integrated into PyIMG4's CLI until then this should suffice.

2023-02-09 06:30 UTC, m1stadev commented on examples/verify-shsh.py
> +    main(build_manifest_path=args.build_manifest, shsh_path=args.shsh, verbose=args.verbose)
In that case, feel free to release your own tool to do so, or just keep the script in your fork. I see no need for the script to be in the upstream repo. If you could remove it from this PR, I'll merge the CLI change.

2023-02-09 07:22 UTC, closed without merging