Adding CLI to attend (#4)
m1stadev/PyIMG4 pull request #5
Opened 2022-05-19 21:18 UTC by doronz88

I'm also considering either scraping TheIphoneWiki or including a JSON file to store all encryption keys.

2022-05-21 17:52 UTC, m1stadev requested changes

2022-05-21 17:52 UTC, m1stadev commented on pyimg4/parser.py
> +    def data(self) -> bytes:
`pyimg4.IM4PData` subclasses `pyimg4._PyIMG4`, which provides the `_PyIMG4.output()` function, which does the same thing, so this is unnecessary.

2022-05-21 18:01 UTC, doronz88 commented on pyimg4/parser.py
> +    def data(self) -> bytes:
👍

2022-05-21 22:51 UTC, m1stadev commented
I'm gonna make the CLI more feature complete before merging, so it may be a while.

2022-05-21 23:35 UTC, doronz88 commented
You mean to the inclusion for both serializing and deserializing of all permutations? I can add this also.

2022-05-21 23:40 UTC, doronz88 commented
Something like:
```shell
pyimg4 im4p create FILENAME DATA [--compression ..] [--key. ..] [--iv ...]
```

2022-05-22 05:33 UTC, m1stadev commented
> You mean to the inclusion for both serializing and deserializing of all permutations? I can add this also.

Yeah. I'll probably work on adding some commands tonight.

2022-05-22 18:06 UTC, doronz88 commented on pyimg4/__main__.py
> +@click.option(
since this is always required and only one parameter its better to be an argument instead of an option

2022-05-22 18:10 UTC, m1stadev commented on pyimg4/__main__.py
> +@click.option(
I'd prefer for it to stay as an option for parity with other commands that do require input as an option

2022-05-22 18:12 UTC, m1stadev commented
I think the CLI should be ready to merge now. @doronz88 do you think there's any other features that should be included?

2022-05-22 18:29 UTC, doronz88 commented
Just for the git history sake, I think its better to rebase it now before merging

2022-05-23 15:04 UTC, m1stadev approved these changes

2022-05-23 15:05 UTC, merged